### ISSUE TITLE
ext_tables.sql misses basketmaxquantity field for table tt_products_articles

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#1]

**Comment by franzholz** [comment]
You use an old version. No basketmaxquantity exists in version 2.7.27 and 2.8.8.

**Comment by webian** [comment]
Right, I was checking out this https://github.com/TYPO3-svn-archive/tt_products.git and I thought to be using your repo https://github.com/franzholz/tt_products.git
Sorry.
