### ISSUE TITLE
PHP Warnings: Missing arguments

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#10]
Hello,
similar to #9 I found also these warnings about missing arguments:

> PHP Warning: Missing argument 2 for tx_ttproducts_field_base::init(), called in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_media.php on line 50 and defined in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_base.php line 50
> PHP Warning: Missing argument 3 for tx_ttproducts_field_base::init(), called in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_media.php on line 50 and defined in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_base.php line 50
> PHP Warning: Missing argument 2 for tx_ttproducts_field_base::init(), called in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_tax.php on line 49 and defined in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_base.php line 50
> PHP Warning: Missing argument 3 for tx_ttproducts_field_base::init(), called in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_tax.php on line 49 and defined in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_base.php line 50
> PHP Warning: Missing argument 2 for tx_ttproducts_field_base::init(), called in htdocs/ext/tt_products/view/class.tx_ttproducts_table_base_view.php on line 137 and defined in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_base.php line 50
> PHP Warning: Missing argument 3 for tx_ttproducts_field_base::init(), called in htdocs/ext/tt_products/view/class.tx_ttproducts_table_base_view.php on line 137 and defined in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_base.php line 50

**Comment by franzholz** [comment]
This seems to be no current version of tt_products.

**Comment by franzholz** [comment]
Answer only on issue #9.

https://github.com/franzholz/tt_products/issues/9
