### ISSUE TITLE
PHP Error Call to a member function getFileInfo() on null in /var/www/html/typo3conf/ext/tt_products/model/field/class.tx_ttproducts_field_media.php

### ISSUE THREAD

**Issue by joshuabeny1999** [franzholz/tt_products#101]
I have following issues in my installation:
Did upgraded to typo 3 v10 and also did the FAL migration. All images are still there in the backend. I have now following Error Message:
![image](https://user-images.githubusercontent.com/55023662/142769283-4a3a6c22-f827-4675-8175-4717a1938d71.png)

It seems something is wrong with getting the storage object. Or did i misconfigured something? Missing tt_products config or Template change?

I installed also the latest tt_products version 2.9.20

**Comment by joshuabeny1999** [comment]
If i disable follwoing line from my template (Comment it yout) I did not see any products anymore but the error is gone....
```
plugin.tt_products.image.imageLinkWrap {
  enable = 1
    typolink {
    ### Note the names of the fields! They are different from the ones tt_content uses! (except imagecaption)
    title.field = imagecaption // imagealttext // imagetitletext
    title.split.token.char = 10
    ### This works only with the imageMarkerFunc!
    title.split.returnKey.data = register : IMAGE_NUM_CURRENT
    title.htmlSpecialChars = 1
    parameter.cObject = IMG_RESOURCE
    parameter.cObject.file.import.data = TSFE:lastImageInfo|origFile
    ATagParams = rel="lightbox[{field:uid}]" class="lightbox"
    ATagParams.insertData = 1
  }
}
```

So it could be possible a template misconfiguration?
My template is located under: https://www.designbyeliane.ch/fileadmin/html/shop.html

**Comment by joshuabeny1999** [comment]
If i replace the problematic line with 
```php
 // $fileInfo = $storage->getFileInfo($fileObj);
$fileInfo = [];
```

Then the shop works but no images are shown.

**Comment by franzholz** [comment]
The first storage is the local file system. This must exist.
Other storages are not supported yet.

**Comment by joshuabeny1999** [comment]
So what could be causing this issue?

**Comment by franzholz** [comment]
I find this code example everywhere. So it is known to work.

    $storageRepository = $this->objectManager->get('TYPO3\\CMS\\Core\\Resource\\StorageRepository');
    $storage = $storageRepository->findByUid('1'); //this is the fileadmin storage
    
Is the fileadmin folder present?
Can you see the images in the TYPO3 backend fileadmin folder?

https://stackoverflow.com/questions/42009425/create-a-filereference-from-a-existing-file-under-fileadmin

**Comment by joshuabeny1999** [comment]
Yeah it is present. But i found the issue. My fileadminfolder has UID 4. If i change the code to following everything works:
```php
$storageRepository = GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\Resource\\StorageRepository');
$storage = $storageRepository->findByUid(4);
```

It seems that it bad that the UID 1 is hardcoded. Here a screenshot of my fileadmin configuration:
![image](https://user-images.githubusercontent.com/55023662/142930641-d2072613-30d2-434c-92d1-70979834e4ca.png)

**Comment by franzholz** [comment]
Would it help if I make the storage uid configurable?

**Comment by joshuabeny1999** [comment]
Yeah that would really help. 

Currently I just edited the code and that would be overwritten by an update. Also I do not know if it used somewhere else than in just this file.

**Comment by alexanderschnitzler** [comment]
Another option here would be to not query storage 1 but query the default storage. In 99.9% of all installations fileadmin is marked as default storage. 

```php
\TYPO3\CMS\Core\Resource\ResourceFactory::getDefaultStorage()
```
