### ISSUE TITLE
Check TCA Migrations wizard fails

### ISSUE THREAD

**Issue by responseinformationsdesign** [franzholz/tt_products#104]
Check TCA Migrations wizard fails because of PHP Warning

`Use of undefined constant TT_PRODUCTS_EXT - assumed 'TT_PRODUCTS_EXT' (this will throw an Error in a future version of PHP) in <path to webroot>\typo3conf\ext\tt_products\Configuration\TCA\sys_products_accounts.php line 12`

PHP is installed in version 7.3.33, TYPO3 in 9.5.31.

**Comment by franzholz** [comment]
This cannot be fixed. Constants are required and commonly used.
Comment this only at ["Check TCA" must include ext_localconf.php](https://forge.typo3.org/issues/95825)  .
