### ISSUE TITLE
PHP Warning 'menucat'

### ISSUE THREAD

**Issue by Hobokens** [franzholz/tt_products#11]
With tt_products 2.8.11 from Github I get the following warning

Core: Error handler (FE): PHP Warning: Declaration of & tx_ttproducts_menucat_view::printView($functablename, &$templateCode, $theCode, &$error_code, $templateArea, $pageAsCategory, $templateSuffix = '') should be compatible with tx_ttproducts_catlist_view_base::printView($functablename, &$templateCode, &$t, &$htmlParts, $theCode, &$error_code, $templateArea, $pageAsCategory, $templateSuffix, &$currentCat, &$categoryArray, &$catArray, &$isParentArray, &$subCategoryMarkerArray, &$ctrlArray) in /www/htdocs/w0144cf7/handspinnerin-hoechberg.de/typo3conf/ext/tt_products/view/class.tx_ttproducts_menucat_view.php line 43

**Comment by franzholz** [comment]
I have fixed this PHP 7 warning now.

https://github.com/franzholz/tt_products/commit/f05805ad07c08f8e6f2404da1b5605985c1689ca
https://github.com/franzholz/tt_products/commit/eacbc293472f641535c21218af5733746b8ee6fc

**Comment by Hobokens** [comment]
thanks a lot for the fast fix
