### ISSUE TITLE
One more error with PHP 7.0.10

### ISSUE THREAD

**Issue by Hobokens** [franzholz/tt_products#12]
`Core: Error handler (FE): PHP Warning: Declaration of tx_ttproducts_content::init(&$cObj, $functablename) should be compatible with tx_ttproducts_table_base::init($cObj, $functablename) in /www/htdocs/xxx/my-domain.de/typo3conf/ext/tt_products/model/class.tx_ttproducts_content.php line 109`

Thanks for the nice extension!
Hobokens

**Comment by franzholz** [comment]
I have fixed this issue now.

https://github.com/franzholz/tt_products/commit/15784aa59405eee9ff3e673d6d469732382f4ab1
https://github.com/franzholz/tt_products/commit/12e9460164fc468c73a15055c55b607377f7c131
