### ISSUE TITLE
Missing cHash in generated urls

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#13]
Hello @franzholz,
i'm on master with TYPO3 7.6.

In `/view/class.tx_ttproducts_basket_view.php`
line 599 `$tempUrl = htmlspecialchars($this->pibase->pi_getPageLink($pid, '', $this->urlObj->getLinkParams('', $addQueryString, TRUE, TRUE, ''),array('useCacheHash' => TRUE)));`
calls `function pi_getPageLink($id, $target = '', $urlParameters = [])`
with `$urlParameters = [ 'tt_products[product]' => 123 ]` 
and with a 4th parameter `array('useCacheHash' => TRUE)` that is not considered because `pi_getPageLink` only generates link to pages and not to records so it doesn't expect a `useCacheHash`.

But the problem is that passing a $urlParameter still creates an entry in RealUrl 2 with a link like `id=4&tt_products[product]=123` that is a duplicate of the same link created before but with the cHash. This causes the detail of the realurl link to display another product or gives 404 depending how RealUrl is configured.

Is it possible to call typoLink directly? Like:
`$tempUrl = $this->pibase->cObj->typoLink('', [ 'parameter' => $pid, 'additionalParams' => '&tt_products[product]=' . intval($row['uid']), 'useCacheHash' => 1, 'returnLast' => 'url']);`

**Comment by franzholz** [comment]
I have fixed this now by using the extension div2007 method getPageLink_fh003.

https://github.com/franzholz/tt_products/commit/bfc60b71563b63f01307be3a98570f6f1faeb108
https://github.com/franzholz/tt_products/commit/c390312176a9f2f7275560411909b3f849387cf7

**Comment by webian** [comment]
Thank you @franzholz it works!

But while checking your commit I found another request without useCacheHash=1:
https://github.com/franzholz/tt_products/blob/master/view/class.tx_ttproducts_single_view.php#L579
because the call to `getPageLink_fh003` is missing the last parameter `array('useCacheHash' => TRUE)`

Please, can you fix also this?

**Comment by franzholz** [comment]
I have fixed now the issue with getPageLink_fh003 for the marker ###FORM_MEMO### in the single and list view.

https://github.com/franzholz/tt_products/commit/9e8cb3a2ad4dcd4846feb1d0e6adab35647b06ea
https://github.com/franzholz/tt_products/commit/f43cbb972ef88ab6e04c0ac07ab4a642871c5700

**Comment by webian** [comment]
Great! Thank you!
