### ISSUE TITLE
Error: Invalid database result detected

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#15]
After introduction of the code in this commit:
https://github.com/franzholz/tt_products/commit/2836899d8a073d956bfc1ccde4baaeda6f508e38
$res is not always set and then, if not set, line https://github.com/franzholz/tt_products/blob/2836899d8a073d956bfc1ccde4baaeda6f508e38/model/class.tx_ttproducts_order.php#L148
generates core error: `Invalid database result detected`

**Comment by webian** [comment]
it can be fixed changing https://github.com/franzholz/tt_products/blob/2836899d8a073d956bfc1ccde4baaeda6f508e38/model/class.tx_ttproducts_order.php#L148 with:
`if ( isset($res) ) { $TYPO3_DB->sql_free_result($res); }`

**Comment by franzholz** [comment]
fixed:

https://github.com/franzholz/tt_products/commit/ce50a881b78a0292ee2ea53683753c10feaef1e6
