### ISSUE TITLE
503 Error after installation

### ISSUE THREAD

**Issue by fxp66** [franzholz/tt_products#156]
Hi Franz,
I've tried to make a fresh installation with Typo 11.5.22 and tt_products last version from git.
After installation 503 error is thrown in the backend.
What is the erason for this?

thx fxp

**Comment by fxp66** [comment]
Core: Exception handler (WEB):  Uncaught TYPO3 Exception: Unclosed '[' on line 226 does not match ')'

I think this is the cause of this

**Comment by franzholz** [comment]
line 226 of which file?

**Comment by fxp66** [comment]
Core: Exception handler (WEB):  Uncaught TYPO3 Exception: Unclosed '[' on line 226 does not match ')' \|  ParseError thrown in file  /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/Configuration/TCA/Overrides/tt_products.php  in line 251. Requested URL:  https://boot12.raco.gmbh/typo3/ajax/system-information/render?token=--AnonymizedToken--&skipSessionUpdate=1

**Comment by fxp66** [comment]
Using version 2.14.8  causes no backend errors but an 503 in the FE with single view:

503 Oops, an error occurred!
Class "GeneralUtility" not found

**Comment by franzholz** [comment]
Please test the current version from Github.

**Comment by fxp66** [comment]
It works, but you have to correct another mistake in 
model/field/class.tx_ttproducts_field_media.php in line 199
same mistake with the closing bracket.

Thanks for your quick help!

**Comment by franzholz** [comment]
fixed:

https://github.com/franzholz/tt_products/commit/826c077eecce27ea2ee1d427633f024a0138fb8e

**Comment by webian** [comment]
@franzholz if you use any modern IDE like [PhpStorm ](https://www.jetbrains.com/phpstorm/) or [Visual Studio Code](https://code.visualstudio.com/), you can easily avoid syntax errors like these because they mark them clearly.

**Comment by franzholz** [comment]
Is there any more error?

**Comment by fxp66** [comment]
Hi Franz,

there are still a lot of errors and warnings:

Core: Error handler (FE): PHP Warning: Trying to access array offset on value of type null in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/field/class.tx_ttproducts_field_delivery_view.php line 90 

Core: Error handler (FE): PHP Warning: Undefined array key "shipping." in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/Classes/Api/PaymentShippingHandling.php line 1733

Core: Error handler (FE): PHP Warning: Undefined array key "cat" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/class.tx_ttproducts_single_view.php line 573 

Core: Error handler (FE): PHP Warning: Undefined array key "ALL." in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_orderaddress.php line 74 

Core: Error handler (FE): PHP  Warning: Undefined variable $useBackPid in  /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/class.tx_ttproducts_url_view.php  line 119

Core: Error handler (FE): PHP  Warning: Undefined variable $creditpointsObj in  /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_basket_calculate.php  line 794

Core: Error handler (FE): PHP Warning: Undefined array key "calculationScript" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/Classes/Api/PaymentShippingHandling.php line 1350 

Core: Error handler (FE): PHP  Warning: Undefined array key "payment." in  /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/control/class.tx_ttproducts_control_basket.php  line 268

...and last...

Oops, an error occurred! Code: 2023011813400383e4c9e3 

....on the single view site

best regards Felix

**Comment by franzholz** [comment]
"!Oops, an error occurred! Code: 2023011813400383e4c9e3"


What does this mean?

**Comment by fxp66** [comment]
If you follow the link "Item details" in list view this error is thrown on the detail site.
Don't know what it means but I guess it is caused by this:

Core: Error handler (FE): PHP Warning: Undefined array key "cat" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/class.tx_ttproducts_single_view.php line 573

**Comment by franzholz** [comment]
I have fixed all warning messages.

https://github.com/franzholz/tt_products/commit/092ac930c530605008f3ddb3c69c6c3bb0f3903e

**Comment by franzholz** [comment]
"Oops, an error occurred! Code: 2023011813400383e4c9e3"

This just means that a severe error occured on 2023, January 18th at 15:26:27.

2023-01-18T15:26:27

But you must look into your PHP error_log file about the file and line number.

**Comment by fxp66** [comment]
Hi Franz,

after installing the debuged version I ran into a lot of new warnings, as you may see:

Core: Error handler (FE): PHP Warning: Undefined variable $priceNumTax in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/field/class.tx_ttproducts_field_price.php line 806

Core: Error handler (FE): PHP Warning: Undefined variable $useBackPid in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/class.tx_ttproducts_url_view.php line 222

Core: Error handler (FE): PHP Warning: Undefined variable $useBackPid in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/class.tx_ttproducts_url_view.php line 182 

Core: Error handler (FE): PHP Warning: Undefined variable $upperField in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/field/class.tx_ttproducts_field_datafield_view.php line 190

Core: Error handler (FE): PHP Warning: Undefined array key "unit" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/class.tx_ttproducts_product_view.php line 271 

Core: Error handler (FE): PHP Warning: Undefined variable $priceNumTax in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/field/class.tx_ttproducts_field_price.php line 806 

Core: Error handler (FE): PHP Warning: Undefined variable $IsGift in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/class.tx_ttproducts_list_view.php line 2552 

Core: Error handler (FE): PHP Warning: Undefined array key "price0tax" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_basket_calculate.php line 409 

Core: Error handler (FE): PHP Warning: Undefined array key "price0tax" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_basket_calculate.php line 399 

Core: Error handler (FE): PHP Warning: Undefined array key "depositnotax" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_basket_calculate.php line 384 

Core: Error handler (FE): PHP Warning: Undefined array key "calc_add" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_basket_calculate.php line 326

Core: Error handler (FE): PHP Warning: Undefined array key "gift." in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_basket_calculate.php line 322

Core: Error handler (FE): PHP Warning: Undefined array key "ext" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/control/class.tx_ttproducts_control_basket.php line 579 

Core: Error handler (FE): PHP Warning: Undefined array key "image." in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/view/field/class.tx_ttproducts_field_media_view.php line 669 

Core: Error handler (FE): PHP Warning: Undefined array key "prodCategory" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_category_base.php line 178

Core: Error handler (FE): PHP Warning: Undefined array key "1 kategorie" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_category.php line 290 

Core: Error handler (FE): PHP Warning: Undefined array key "" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_category.php line 186

Core: Error handler (FE): PHP Warning: Undefined array key "special." in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_category.php line 447

Core: Error handler (FE): PHP Warning: Undefined array key "special." in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_category.php line 438

Core: Error handler (FE): PHP Warning: Undefined array key "product" in /var/www/vhosts/raco-elektro-maschinen.gmbh/boot12.raco.gmbh/typo3conf/ext/tt_products/model/class.tx_ttproducts_basket.php line 154

Still there is this "Ooops..." error on the single view but no hint in logs.

I'm quite sure to have tt_products setup well. Any idea to solve this?

best regards
Felix

**Comment by franzholz** [comment]
Make a new bug for these warnings.

Use the extensions fh_debug and debug_mysql_db to track down the reason for the "oops" error.

**Comment by fxp66** [comment]
Thanks for your advise. This "Ooops.." error was caused by a missing file.

tt_products/res/icons/fe/availableImmediate.gif

The whole directory is missing. After adding everythings works fine.

Thanks Felix

**Comment by franzholz** [comment]
Use this fix:

https://github.com/franzholz/tt_products/commit/c956816320a2e2b8f78046124d89f1e55f46bc24
