### ISSUE TITLE
503 Issue

### ISSUE THREAD

**Issue by fxp66** [franzholz/tt_products#163]
Hi Franz,

please give me a hint about this:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT COUNT(*) FROM `tt_products`.`backup` WHERE `tt_products`.`backup`.`pid` = ? LIMIT 1' with params [3]: SELECT command denied to user 'yyyy'@'localhost' for table 'backup' | Doctrine\DBAL\Exception\ConnectionException thrown in file /var/www/vhosts/raco-elektro-maschinen.gmbh/yyyy.de/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 112. Requested URL: https://yyyy.de/typo3/module/web/list?token=--AnonymizedToken--&id=3 `

I use 2.14.12

Thanks felix

**Comment by franzholz** [comment]
I have no idea how you came into this SQL error.

**Comment by franzholz** [comment]
What is the table "tt_products.backup" about? Why don't you simply use the table "tt_products"?

**Comment by fxp66** [comment]
I'm using tt_products now for 8 years as catalog.
This is a great tool, because our industrial products are very complecated. I've altered the table with a lot of necassary values, so i have always issues, when running a major update. So i made a backup, but forgot, where the query is located. I lost the last year because of cancer, but now started working again and have probs remembering details of my former doing.

**Comment by franzholz** [comment]
**SELECT command denied to user 'yyyy'@'localhost' for table 'backup'**
 
 So you have a user 'yyyy' with missing SELECT rights.

**Comment by franzholz** [comment]
This could also be related to #166
