### ISSUE TITLE
setup of tt_products 2.14 no products shown

### ISSUE THREAD

**Issue by averlon** [franzholz/tt_products#166]
Hi,
I have tried to setup tt_products from scratch in a T3 11.5 installation.

- tt_products included in template
- sysfolder with one product and some categories
- page with "Products:list" - where sysfolder is assigned

FE does not show any product.

- page with "Category:menu" - Category tree is shown

I created my own template. Just:
`    <h2>ITEM_LIST_TEMPLATE</h2>
    <p><em>This subpart is used to display the regular list of products. It's also used by search-results.</em></p>
    
      <div>xxx</div>
    
    <br><br>
`
Nothing is shown!

Any idea?

jambagecom/tt-products                     v2.14.12 Shop system extension for TYPO3 CMS

**Comment by averlon** [comment]
![grafik](https://user-images.githubusercontent.com/7830373/216994555-97a139c0-c7fb-418d-a161-571fde5fcf35.png)

![grafik](https://user-images.githubusercontent.com/7830373/216994694-9a2fd242-6b1a-4367-87dc-881a7d70c1c0.png)

![grafik](https://user-images.githubusercontent.com/7830373/216994802-731767ec-94dc-4271-8574-b21137b3477b.png)

![grafik](https://user-images.githubusercontent.com/7830373/216994906-089223ad-57cf-4f28-ab96-c65b67a00c86.png)

brings an "Oops ..." error.

**Comment by franzholz** [comment]
"Oops ..." is no valid error report. You must provide all the details.

Use a debug extension or search your log files.

**Comment by averlon** [comment]
I know. But it is not that easy for me to find out more details.
My log does not say anything on this - what i already checked. I probably have to increase the apache log level - I will give it a try.
I will look for a debug extension - if you can recommend - I would appreciate. So far I did not have to use such as pure admin (not being a developer).

**Comment by averlon** [comment]
Oh - I saw there is one from your hand. Will try it!

**Comment by averlon** [comment]
I have tried to setup the debug extension but failed. Once this is in the system even the BE does not show anything anymore. Thats not a way forward - at least not for me!

**Comment by franzholz** [comment]
What does this mean: "BE does not show anything anymore"?
You must activate the Application Context: Developmen!

Which debug extension did you install?

**Comment by averlon** [comment]
I tried "composer req jambagecom/fh-debug" - I think your extension - as I wrote before.
Since I am not a programmer, I tried to follow the docu. I did not see a hint the Application Context: Development is a prerequisit.

I will try again!

**Comment by averlon** [comment]
Ok.
I have installed the extension via composer!
- Context: Development is set via Apache ReWrite.
- I have switched "GlobalDebugFunctions.php"

`'SYS' => [
        'caching' => [
           ...
        ],
        'devIPmask' => '',
        'displayErrors' => 0,
        'encryptionKey' => '15f6f0fa530ec2d8421e522a87acd38200da2525a97b03d9eec495a630571e9dd78b92be21822c23bd8f99391704dc57',
        'exceptionalErrors' => 4096,
        'features' => [
            'felogin.extbase' => true,
            'fluidBasedPageModule' => true,
            'rearrangedRedirectMiddlewares' => true,
            'unifiedPageTranslationHandling' => true,
            'yamlImportsFollowDeclarationOrder' => true,
        ],
        'mediafile_ext' => 'gif,jpg,jpeg,bmp,png,pdf,svg,ai,mp3,wav,mp4,ogg,flac,opus,webm,youtube,vimeo',
        'phpTimeZone' => 'Europe/Berlin',
        'productionExceptionHandler' => 'JambageCom:raw-latex:FhDebug',
        'sitename' => 'AvHome',
        'systemMaintainers' => [
            1,
            3,
        ],`

Now the BE is shown, but only the left hand side part where I can choose the applications. Also the page tree is shown. But whatever I click, nothing happens. BE is - I would say - "frozen".

**Comment by averlon** [comment]
I will stop working on this. Seems to be my knowledge is not good enough for this.

Close Ticket!

**Comment by franzholz** [comment]
Well, you have deactivated all error output:

devIPmask' => '', 'displayErrors'

Both must be set in order to see the error display.

**Comment by averlon** [comment]
I have now setup a clean t3 installation.
only tt_products (and Bootstrap-Package)
no own TS for tt_products
sysfolder set by BE-Form

Unfortunately the Dump.html is not filled.

If 'displayErrors' => other then 1, I get an exception error. The php-module is changed.

`
(1/1) #3065 mysqli_sql_exception

Expression #1 of ORDER BY clause is not in SELECT list, references column 'av_t3test.tt_products_cat.sorting' which is not in SELECT list; this is incompatible with DISTINCT
`

**Comment by franzholz** [comment]
Here is the solution:

https://stackoverflow.com/questions/36829911/how-to-resolve-order-by-clause-is-not-in-select-list-caused-mysql-5-7-with-sel


**sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"**
