### ISSUE TITLE
Translated Record is not Showing after Upgrade from 9.5 to 11.x

### ISSUE THREAD

**Issue by nilesh-nitsan** [franzholz/tt_products#182]
TYPO3 Old version: 9.5.22
Upgraded version: 11.x

After upgrading the projects the listing of tt_products not showing any more in translated pages. 

![image](https://user-images.githubusercontent.com/59409022/232389981-fe374e4c-ce59-4be2-80a7-b9da46062ccb.png)

can you please give hint or any thing I missed? I have followed all upgrade wizards. 

Thank & help is appreciable.

**Comment by franzholz** [comment]
Check with the extension debug_mysql_db if you have any SQL error message.

**Comment by nilesh-nitsan** [comment]
Yes, I have checked with extension, there is not any single SQL error message

**Comment by roblahnst** [comment]
Ich habe das gleiche Problem.
Vorherige Typo3 version: 9.5.22
Vorheriges tt_products: 2.9.11
Vorherige table: 0.7.7
Vorherige mbi_products_categories: 0.7.8
Vorherige div2007: 1.10.32

Jetzt Typo3 version: 11.5.26 und php 8.1.18
und sonst alle neuesten tt_products und abhängigen extensions.
Die Produkte mit Language version 0 werden angezeigt, aber die Produkte mit language version 1-3 kommen nicht.

**Comment by franzholz** [comment]
only English allowed here

Check the starting point of the plugins or use the pid_list setup instead of it.

**Comment by nilesh-nitsan** [comment]
Hi 

I have set pid_list also, but still, nothing changed same error was shown to me in the second language:

![image](https://user-images.githubusercontent.com/59409022/236202015-56fb897b-294a-46e7-b821-3774dbbb1fe0.png)

**Comment by franzholz** [comment]
You must look for the generated SQL by help of the extension debug_mysql_db.
Then you will see that this SQL query gives no results. Then you remove some items from the WHERE clause and by the help of MySqlAdmin you will find the SQL which will work. Then this information gives you the exact reason what is wrong in your configuration.

**Comment by roblahnst** [comment]
The extension debug_mysql_db works fine with typo3 version 10 (old system) and shows the SQL command

SELECT product.uid uid FROM tt_products product LEFT OUTER JOIN tx_mbiproductscategories_mm ON product.uid = tx_mbiproductscategories_mm.uid_local,tt_products_language productlang WHERE product.uid = productlang.prod_uid AND productlang.pid IN (53) AND tx_mbiproductscategories_mm.uid_foreign IN (9010000,9020000,9030000,9040000) AND productlang.deleted=0 AND productlang.hidden=0 AND (productlang.starttime<=1683290874) AND (productlang.endtime=0 OR productlang.endtime>1683290874) AND productlang.fe_group IN (' ',0,-1) AND productlang.deleted=0 AND productlang.hidden=0 AND (productlang.starttime<=1683290874) AND (productlang.endtime=0 OR productlang.endtime>1683290874) AND productlang.fe_group IN (' ',0,-1)  AND productlang.sys_language_uid=1

But with typo3 version 11 the debug_mysql_db extension throws an error itself. Cannot see the SQL code at all.

**Comment by franzholz** [comment]
There is no known error with the extension debug_mysql_db.
Report any error directly to that extension.

**Comment by roblahnst** [comment]
Reported the error. Then fixed it by commenting the line $this->checkConnectionCharset(); in DatabaseConnection.php.

Now it shows a difference and also gets a different result in phpmyadmin:
SELECT product**lang**.uid uid FROM tt_products product LEFT OUTER JOIN tx_mbiproductscategories_mm ON product.uid = tx_mbiproductscategories_mm.uid_local,tt_products_language productlang WHERE product.uid = productlang.prod_uid AND productlang.pid IN (53) AND tx_mbiproductscategories_mm.uid_foreign IN (9010000,9020000,9030000,9040000) AND productlang.deleted=0 AND productlang.hidden=0 AND (productlang.starttime<=1683370283) AND (productlang.endtime=0 OR productlang.endtime>1683370283) AND productlang.fe_group IN (' ',0,-1) AND productlang.deleted=0 AND productlang.hidden=0 AND (productlang.starttime<=1683370283) AND (productlang.endtime=0 OR productlang.endtime>1683370283) AND productlang.fe_group IN (' ',0,-1) AND productlang.sys_language_uid=1

How can I change this SELECT statement to be like the previous one?

**Comment by franzholz** [comment]
Where is this SQL executed?

**Comment by roblahnst** [comment]
It is executed on a server that runs an upgraded version of typo3 and tt_products and doesn’t lead to the expected result. This has all been described before. The code has a bug and this is a question to the developer how to fix the problem and at the same time to help to improve the code.

**Comment by franzholz** [comment]
Yes, of course.
But I need the exact PHP file name and line number, where the SQL with the error is executed.

**Comment by roblahnst** [comment]
This is the full output:
array(5 items)
   function/mode => 'Pg exec_SELECTquery(tt_products product LEFT OUTER JOIN tx_mbiproductscatego
      ries_mm ON product.uid = tx_mbiproductscategories_mm.uid_local,tt_products_l
      anguage productlang) - class.tx_table_db.php#1713->exec_SELECTquery // class
      .tx_table_db.php#1587->exec_SELECTquery // Typo3DbLegacyConnection.php#250->
      myDebug' (311 chars)
   SQL query => 'SELECT productlang.uid uid FROM tt_products product LEFT OUTER JOIN tx_mbipr
      oductscategories_mm ON product.uid = tx_mbiproductscategories_mm.uid_local,t
      t_products_language productlang WHERE product.uid = productlang.prod_uid AND
       productlang.pid IN (53) AND tx_mbiproductscategories_mm.uid_foreign IN (901
      0000,9020000,9030000,9040000) AND productlang.deleted=0 AND productlang.hidd
      en=0 AND (productlang.starttime<=1683446827) AND (productlang.endtime=0 OR p
      roductlang.endtime>1683446827) AND productlang.fe_group IN (' ',0,-1) AND pr
      oductlang.deleted=0 AND productlang.hidden=0 AND (productlang.starttime<=168
      3446827) AND (productlang.endtime=0 OR productlang.endtime>1683446827) AND p
      roductlang.fe_group IN (' ',0,-1)  AND productlang.sys_language_uid=1' (753 chars)
   num_rows() => 22 (integer)
   miliseconds => 6.202 (double)
   ------------ => '' (0 chars)

If this is not what you need, where can I find it?

**Comment by franzholz** [comment]
The bug trace of the filenames together with line numbers is missing.
Use the extension **fh_debug** in order to get these lines also.

Extension Configuration in Backend:

_Depth of the trace
basic.TRACEDEPTH (int+)_

You can additionally activate the debug trace in **debug_mysql_db**.

Extension Configuration in Backend:

_BTRACE_SQL = 1_
However this uses the TYPO3 debug trace which is less readable than the trace from fh_debug.

**Comment by roblahnst** [comment]
I understand that fh_debug only works in case of an “Oops, an error occurred!”.
But this is not the case. There is no such error, there is just no output, because the SQL statement looks in the wrong table. It looks in tt_products_language, but it should look in tt_products.

**Comment by franzholz** [comment]
No, fh_debug will debug all generated output, if you change debug_mysqL_db in order to use the function 'debug' for generating of the output HTML file. 
Use this for fh_debug:

_OUTPUT = debug_

**Comment by franzholz** [comment]
Check it with latest tt_products 2.14.16 and table 0.12.1.
