### ISSUE TITLE
tt_products and div2007

### ISSUE THREAD

**Issue by shuffgy** [franzholz/tt_products#20]
> Fatal error: Interface 't3lib_Singleton' not found in /html/typo3/typo3conf/ext/tt_products/pi1/class.tx_ttproducts_pi1.php on line 47

TYPO3 7.6.18 with all dependencies from the extmanager installed.

If i want to display categories or products as a list (or something else) it throws the fatal error in backend and frontend. 

Am I doing something wrong?

**Comment by franzholz** [comment]
This bugtracker is only in English.

**Comment by shuffgy** [comment]
@franzholz  updated comment...

**Comment by franzholz** [comment]
div2007 1.7.6 must be installed.

https://github.com/franzholz/div2007/releases/tag/Version-1-7-6

It contains all the migration classes necessary for TYPO3 7.x and 8.x.

**Comment by shuffgy** [comment]
with 1.7.6 i'm getting

> Fatal error: Only variables can be passed by reference in /html/typo3/typo3conf/ext/div2007/class.tx_div2007_alpha5.php on line 2744

**Comment by franzholz** [comment]
Hierbei handelt es sich um eine unbekannte Extension, die eine zu PHP 5 nicht kompatible Hook Funtikon verwendet.

    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_page.php']['addEnableColumns'] 

Also den PHP Code dieser unbekannten Extension auf PHP 5 Kompatibilität bringen. Denn es sollten keine Referenzen auf Parameter verwendet werden, wie z.b. '&pObj'. In PHP 5 wird ein Objekt immer als Referenz übergeben.

In div2007 ist es nicht möglich, einen Aufruf, wie diesen aus ./typo3/sysext/frontend/Classes/Page/PageRepository.php zu verwenden:

    $query .= GeneralUtility::callUserFunction($_funcRef, $_params, $this);

Denn div2007_alpha5.php ist statisch.  Und ich meine, dass dieses Vater Objekt nicht benötigt wird.

**Comment by franzholz** [comment]
This is caused by an unknown extension, which uses a hook function that is incompatible with PHP 5.

    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_page.php']['addEnableColumns'] 

No references to object parameters shall be used as e.g. '&pObj'. In PHP 5 an object is always passed as a reference.

In div2007 something like this from ./typo3/sysext/frontend/Classes/Page/PageRepository.php is not possible:

    $query .= GeneralUtility::callUserFunction($_funcRef, $_params, $this);

This is because div2007_alpha5.php is a static class.  And I think that a parent object is needed nowhere.

**Comment by mesurinna** [comment]
I just solved the error by changing : 
```
foreach ($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_page.php']['addEnableColumns'] as $_funcRef) {
    $query .= t3lib_div::callUserFunction($_funcRef, $_params, 'tx_div2007_alpha5');
}
```

to:

```
$tx_p = 'tx_div2007_alpha5';
foreach ($GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_page.php']['addEnableColumns'] as $_funcRef) {
    $query .= t3lib_div::callUserFunction($_funcRef, $_params, $tx_p);
}
```

**Comment by franzholz** [comment]
There is a bug in div2007 on the line you posted here. The callUserFunction needs always a variable reference as the third parameter.

https://github.com/franzholz/div2007/commit/a958af87bad5b59d44ac6e93dfa116a032fb43ca
