### ISSUE TITLE
Page Browse routeEnhancers don´t work

### ISSUE THREAD

**Issue by quadronet** [franzholz/tt_products#203]
Tt_products v. 3.2.1 , the page browser don´t work:

Oops, an error occurred!
Parameter "tt_products__pp" for route "enhancer_tt_products000000006f6f18f000000000360c3551" must match "[a-zA-Z0-9].*" ("-1" given) to generate a corresponding URL.

**Comment by franzholz** [comment]
See the example config.yaml here on the Wiki pages.

**Comment by quadronet** [comment]
This file don´t work too. 

The pagebrowser don´t work, the example Link: https://www.kimmle.1qn.de/weinshop/weissweine/?tt_products%5Bpp%5D=-1&cHash=d40cdd1c1e53bec32632b8da678050c3

**Comment by franzholz** [comment]
What does not work? But there is no error message.

**Comment by quadronet** [comment]
on this site whitewine are 28 wine bottles, you can switch to the next site (page2).

**Comment by franzholz** [comment]
But this has nothing to do with the config.yaml file.

https://mydomain.com/weinshop/weissweine/?tt_products%5Bpp%5D=-1&cHash=d40cdd1c1e53bec32632b8da678050c3 

You have tt_products[pp]=-1 as parameter. So this leads to nowhere.

**Comment by quadronet** [comment]
I don't know that I have entered anything with -1 anywhere. Where would that come from?

**Comment by franzholz** [comment]
I have never seen this. I cannot use your outdated version of tt_products.
Check it with a supported version of tt_products.

**Comment by quadronet** [comment]
It is your tt_products version 3.4.0

**Comment by franzholz** [comment]
Version 3.4.3 is required then.
