### ISSUE TITLE
MySQL STRICT mode 

### ISSUE THREAD

**Issue by quadronet** [franzholz/tt_products#205]
When will the shop run under PHP 8.1 and 8.2? 

At the moment PHP 8.2 gives this error when displaying the products: 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1140: Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause | mysqli_sql_exception thrown in file /var/www/vhosts/domain.de/domain.de/typo3conf/ext/typo3db_legacy/Classes/Database/DatabaseConnection.php in line 488.

**Comment by franzholz** [comment]
This is no error with a PHP version.
See the Wiki page for the required MySQL settings.

**Comment by quadronet** [comment]
did you mean this site: https://github.com/franzholz/tt_products/wiki/Error-Cases? 
This is set:
'DB' => [
    'Connections' => [
        'Default' => [
            'host' => 'localhost',
            'port' => 3306,
            'driver' => 'mysqli',
            'dbname' => 'mydatabase',
            'charset' => 'utf8mb4',
            'tableoptions' => [
                'charset' => 'utf8mb4',
                'collate' => 'utf8mb4_unicode_ci',
            ],
            'user' => 'myuser',
            'password' => 'mypassword',
        ],
    ],
    'extTablesDefinitionScript' => 'extTables.php',
],


But we can´t switch the sql mode on server.

**Comment by franzholz** [comment]
Yes, you must switch the SQL mode in the Mysql configuration.

**Comment by quadronet** [comment]
This means that the store will not be able to run if we cannot change the mysql mode on the server. That really can't be the case.

**Comment by franzholz** [comment]
There is also a quick fix:

class.tx_ttproducts_main.php:  line 265

        $res = $GLOBALS['TYPO3_DB']->sql_query('SET SESSION sql_mode =\'TRADITIONAL\';');

Just add this line.

**Comment by franzholz** [comment]
I have found a bug fix:

https://github.com/franzholz/tt_products/commit/3294391ffb1b45a6c24ec28f15d12a78c376a1a5


    $selectCountConf['leftjoin'] = '';
    $selectCountConf['orderBy'] = '';
    $queryParts =
        $itemTable->getTableObj()->getQueryConf(
            $cObj,
            $tablename,
            $selectCountConf,
            true
        );

Insert those 2 lines before the getQueryConf call with $selectCountConf as parameter in file class.tx_ttproducts_list_view.php .

**Comment by franzholz** [comment]
This is related to 

issue #166
