### ISSUE TITLE
PHP warning messages

### ISSUE THREAD

**Issue by quadronet** [franzholz/tt_products#206]
i became an error on TYPO3 Debug = 1:

#1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "19.00" in /var/www/vhosts/domain.de/domain.de/typo3conf/ext/tt_products/view/class.tx_ttproducts_basket_view.php line 150

                    $label = $calculatedArray['priceNoTax']['sametaxtotal']['ALL'][$taxstr] + $calculatedArray['depositnotax']['sametaxtotal']['ALL'][$taxstr];

**Comment by franzholz** [comment]
Please send me PHP warnings only per E-Mail. It does not make sense to open hundreds of issues on the bugtracker for them.
