### ISSUE TITLE
Incorrect integer value: '' for column `db`.`sys_products_orders`.`radio1` at row 1

### ISSUE THREAD

**Issue by alexanderschnitzler** [franzholz/tt_products#209]
Hello,

when submitting an order, I get the following error:

```
(1/1) #1366 mysqli_sql_exception

Incorrect integer value: '' for column `db`.`sys_products_orders`.`radio1` at row 1
```

That's due to not letting the user submit the radio1 value through the form and the fallback to an empty string in `class.tx_ttproducts_order.php`:

```php
// \tx_ttproducts_order::putRecord()

$fieldsArray['radio1'] = $deliveryInfo['radio1'] ?? '';
```

The fallback should be the default integer value `0`, not an empty string.

**Comment by franzholz** [comment]
Check if this fixes the issue!

**Comment by franzholz** [comment]
see also

https://github.com/franzholz/tt_products/pull/208/commits/be5dfcd95a3c156c1285c0fd0abbc849a87048b0

**Comment by alexanderschnitzler** [comment]
Hey,

all of this does not fix the problem. I just checked with your new release.

The fallback value of `radio1` is now `null` instead of `''`. That's alright, but we still have this table definition:
```sql
radio1 int(11) unsigned DEFAULT '0' NOT NULL,
```
And allowing `null` in the TCA does not help here because the data is stored via direct sql query and not via DataHandler.

**Comment by franzholz** [comment]
The database INSERT automatically fills in the DEFAULT value if nothing has been set. A PHP variable with value null means that it is unset. So the INSERT must work. Check your database table tt_products if it really has DEFAULT 0.
