### ISSUE TITLE
Repeating ITEM_LIST content with every ITEM_SINGLE

### ISSUE THREAD

**Issue by joximu** [franzholz/tt_products#21]
Hello
I use tt_products 2.8.19
I found that in the ###ITEM_LIST_TEMPLATE### the content in ###ITEM_LIST### is repeated with every item in the list (no articles etc, only simple products) -  as if they were written inside ###ITEM_SINGLE###.
Example with example_locallang_xml.html:
theese thre lines are repeated with every product
```
                        <tr>
                                <td colspan=4><img src="clear.gif" width=1 height=6></td>
                        </tr>
```
but they should be placed *once* before the first product - and then never again.
Since theese lines also are used inside the ITEM_SINGLE part - it's difficult to detect.

To reproduce, just put some unique HTML-output in between of here
```
                <!-- ###ITEM_LIST### begin -->
                        <tr>
                                <td colspan=4><img src="clear.gif" width=1 height=6></td>
                        </tr>
                        <!-- ###ITEM_SINGLE### begin-->
```
my "solution" (patch) looks like this - but I'm not sure if it covers every situation:

```
--- class.tx_ttproducts_list_view.php_o 2017-06-04 12:03:49.000000000 +0200
+++ class.tx_ttproducts_list_view.php   2017-07-12 10:19:49.058727799 +0200
@@ -1812,7 +1812,7 @@
                                                                }
                                                        }
                                                        $subpartArray['###ITEM_SINGLE###'] = $itemsOut;
-                                                       $itemListOut .= $this->cObj->substituteMarkerArrayCached($t['itemFrameWork'], $markerArray, $subpartArray, $wrappedSubpartArray);
+                                                       $itemListOut .= $this->cObj->substituteMarkerArrayCached($t['item'], $markerArray, $subpartArray, $wrappedSubpartArray);
                                                        $itemsOut = '';
                                                }
                                                $iColCount = 0; // restart in the first column
@@ -1869,6 +1869,8 @@
                                                }
                                        }
                                }       // foreach ($itemArray as $k1 => $productList) {
+                                                       $subpartArray['###ITEM_SINGLE###'] = $itemListOut;
+                                                       $itemListOut = $this->cObj->substituteMarkerArrayCached($t['itemFrameWork'], $markerArray, $subpartArray, $wrappedSubpartArray);
                        } else {
                                if (isset($catTableConf['subpart.']))   {
                                        $displayCat = $cat;
```

Thanx

**Comment by franzholz** [comment]
The subpart marker structure is this:

    ###ITEM_LIST_TEMPLATE###  
        ###ITEM_CATEGORY_AND_ITEMS###
            ###ITEM_CATEGORY###
            ###ITEM_LIST###
                 ###ITEM_SINGLE###

The ITEM_LIST part is repeated according to the constant displayBasketColumns (deprecated).
Use instead the complex setup

     plugin.tt_products.conf.tt_products.LIST.displayColumns {
          1 = 3
      }

The  ###ITEM_LIST### is repeated according to the defined number of columns. This can be set to 1. This is needed because some HTML might be inserted for each column of products.
