### ISSUE TITLE
Issue with typo3 1.15.34 extension manage: div2007 was requested for download in different versions (1.14.8 and 1.15.2).

### ISSUE THREAD

**Issue by rhabacker** [franzholz/tt_products#233]
I am facing a dependency issue when using this extension with typo3 1.15.34.

In the extension manager of the typo3 backend I get the following exception:
```
(1/1) #1342432101 TYPO3\CMS\Extensionmanager\Exception\ExtensionManagerException

div2007 was requested for download in different versions (1.14.8 and 1.15.2).
```

I have installed [`jambagecom/tt-products#v2.15.0`] (https://packagist.org/packages/jambagecom/tt-products#v2.15.0)
- this package depends on [jambagecom/div2007](https://packagist.org/packages/jambagecom/div2007#v1.15.2): ^1.15
    - which replaces typo3-ter/div2007: v1.15.2 
- [jambagecom/table](https://packagist.org/packages/jambagecom/table#v0.11): ^0.11
    - depends on typo3-ter/div2007: ^1.12 || ^1.13 || ^1.14

which in my opinion creates the conflict.

I think that the conflict can be solved on https://github.com/franzholz/tt_products/blob/a711301d24b583e22fe52b5474d57a35a7ef3119/composer.json#L30 by increasing the dependency on the `jambagecom/table` package to at least `^0.13` (see https://packagist.org/packages/jambagecom/table#v0.13.0)

**Comment by franzholz** [comment]
This should be working with tt_products 2.15.2.
