### ISSUE TITLE
Changed query parameters for links to single view

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#24]
Hello @franzholz 
after this commit https://github.com/franzholz/tt_products/commit/1c35255f8770817006eaf2bcb28c82dc6044790f
links to single view has query parameters `product=123` instead of the classic `tt_products[product]=123`.
Is this a wanted behaviour?

**Comment by franzholz** [comment]
I cannot verify such a behaviour. Of course this won't change.
These are example parameters:

    tt_products[backPID]=11&tt_products[product]=11&cHash=f498efb6d0759c0567a2e653859d5943

**Comment by webian** [comment]
Thanks for the fix!
