### ISSUE TITLE
Several TCA issues

### ISSUE THREAD

**Issue by LightsOnDeveloper** [franzholz/tt_products#243]
Hello Mr. Holzinger,

I got this error by checking TCA in ext_tables.php in admin tools > upgrade in typo3 11.5 with the current main version of tt_products.

**Comment by franzholz** [comment]
You have not given the version number of tt_products.
Try it out with the most recent version of tt_products and also the master branch on Github.

**Comment by LightsOnDeveloper** [comment]
I use the current version of tt_products in TER. Thats the version 2.15.3.

**Comment by LightsOnDeveloper** [comment]
thank you. I check this fix.

**Comment by LightsOnDeveloper** [comment]
The fix works. However, the next error appears immediately. Has EXTCONF not changed to EXTENSIONS?
I have now changed this everywhere in the TCA files. This would fix the errors. 

But then an error appears with "Undefined constant "JambageCom\TtProducts\Domain\Model\Dto\TT_PRODUCTS_EXT"". Here I have adjusted the following in Model EmConfiguration.php:
TT_PRODUCTS_EXT changed to 'tt_products'

Then all error messages are solved after clicking "Check TCA" in admin tools.

**Comment by franzholz** [comment]
Give me the details what needs to be changed.

**Comment by LightsOnDeveloper** [comment]
All definitions with $GLOBALS['TYPO3_CONF_VARS']['EXTCONF'][$extensionKey] in the hole TCA files thrown the error, that array key 'tt_products' are undefined.

Did you doesn't get the error by checking the tca configuration in admin tools > upgrade > "Check TCA"?

**Comment by LightsOnDeveloper** [comment]
I changed this to $GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'][$extensionKey]

**Comment by franzholz** [comment]
This should fix the error:

https://github.com/franzholz/tt_products/commit/6e919cdb21bda3c1ac2c2f3adc144933c1ecd6a0

**Comment by LightsOnDeveloper** [comment]
Hey,
sorry for my late response. I have test it and it doesn't work. I would propose, that I send you a message to your mail address .

**Comment by franzholz** [comment]
Which error message do you get? I could not find anything wrong.

**Comment by franzholz** [comment]
Make a new issue for other improvements.
