### ISSUE TITLE
Allow to customize single view page title

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#25]
This solution is too strong:
https://github.com/franzholz/tt_products/blob/master/Classes/Hooks/ContentPostProcessor.php

It's hard to set a custom title (i.e.: with typoscript) after tt_product replace its own in the rendered HTML.

**Comment by franzholz** [comment]
Can you add a patch or sponsor an improvement?
More details for your use case are needed.

**Comment by webian** [comment]
I need a title tag like this:
`product-title` - `category-title` - `site-title`
this title is used also in meta og:title.

Usually I make this in typoscript. Now I also have to unset tt_products contentPostProc hooks.
Not a big deal but also not an elegant solution.

**Comment by franzholz** [comment]
I could make this hook configurable in the Extension Manager, so it will do nothing. Would this be helpful?

**Comment by webian** [comment]
Yes, better than unset the hook as I did.

**Comment by franzholz** [comment]
Check this out:

https://github.com/franzholz/tt_products/commit/fbeee7557fd28be23f0546b884ce900795e6581f

**Comment by webian** [comment]
Ok, but why inside "cache" tab?
![](https://i.imgur.com/3HcxXHT.jpg)

**Comment by franzholz** [comment]
Sorry. I have fixed this now.

**Comment by webian** [comment]
Perfect! Thank you.
