### ISSUE TITLE
Wrong ###FORM_URL### link in ###BASKET_INFO_TEMPLATE###

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#26]
After this https://github.com/franzholz/tt_products/commit/e8331dbdbba6b05396e4ab204c478826af1c86ca the ###FORM_URL### link in ###BASKET_INFO_TEMPLATE### points to the info page itself instead of the link to the basket, so the user can't proceed with the order.

**Comment by franzholz** [comment]
I think that the shop template should be modified. Why example shop template do you use. The ###FORM_URL### should normally remain on the current page. It is not sure that the entered information is correct. An `onclick` javascript should be added to the button which proceeds to the payment page.

**Comment by webian** [comment]
Ok, I got it, thank you.
I replaced ###FORM_URL### with ###FORM_URL_BASKET### in ###BASKET_INFO_TEMPLATE### to solve this.
