### ISSUE TITLE
tt_products 3.5.0 and container and grid_for_container do not work together

### ISSUE THREAD

**Issue by quadronet** [franzholz/tt_products#264]
After installing tt_products 3.5.0, the container and grid_for_container extension no longer works. No content can be stored in the created containers. All container elements are affected. 
[typo3_e27a65be38.log](https://github.com/user-attachments/files/15757170/typo3_e27a65be38.log)
Picture without working function:
![bild-ohne-funktion](https://github.com/franzholz/tt_products/assets/3660985/1c5d03e2-6502-42ec-bb9c-0240668dc256)
Picture with working function:
![bild-mit-funktion](https://github.com/franzholz/tt_products/assets/3660985/a5a7c7ba-1908-4819-803d-b97b91298fe4)

**Comment by franzholz** [comment]
There is nothing useful in the logfiles.

**Comment by franzholz** [comment]
Which picture is this? How do you get it?
Is there an entry in the PHP error log or anywhere else when you go to the backend module where you produce this picture?

**Comment by franzholz** [comment]
This has been fixed in extension div2007.

https://github.com/franzholz/div2007/commit/81fc73a80d94f4a7c68f5c4a017706e40cdee757
