### ISSUE TITLE
Search PHP Warning Undefined array key

### ISSUE THREAD

**Issue by LightsOnDeveloper** [franzholz/tt_products#265]
We got an error after searching for a product with this message:

PHP Warning: Undefined array key "" in /var/www/html/vendor/jambagecom/table/lib/class.tx_table_db.php line 135

TYPO3: 12.4.15
tt_products: 2.15.7
PHP: 8.1.24

**Comment by franzholz** [comment]
I also need the backtrace in order to know where the method getLangAlias has been called. Activate the debug output.

**Comment by franzholz** [comment]
Try out this fix:

https://github.com/franzholz/table/pull/7

**Comment by LightsOnDeveloper** [comment]
The fix works! Thank you and sorry for my late response.
