### ISSUE TITLE
PHP Warning: Undefined array key "groupBy"

### ISSUE THREAD

**Issue by LightsOnDeveloper** [franzholz/tt_products#270]
Hello Mr. Holzinger,

next problem with table ext. After click on the order-button I got the following error:
PHP Warning: Undefined array key "groupBy" in /var/www/html/vendor/jambagecom/table/lib/class.tx_table_db_access.php line 137

**Comment by franzholz** [comment]
This error is not within tt_products. And it also seems to be not of the latest version of extension table either.

**Comment by LightsOnDeveloper** [comment]
But it occurs in the table. All versions required for tt_products are up to date with the latest TER version, just like tt_products. If you are of the opinion that it does not occur within the tt_products, then probably as the error message says in the table. If you wish, I can create a corresponding ticket there. However, this is an active application and customers cannot order anything.

**Comment by franzholz** [comment]
Test it with the current development branch of the table extension.
