### ISSUE TITLE
Wrong priceNoTax vouchertotal

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#29]
calculatedArray['priceNoTax']['vouchertotal'] is calculated wrongly here: https://github.com/franzholz/tt_products/blob/master/model/class.tx_ttproducts_basket.php#L1187
because `$voucherAmount` should be without taxes.

**Comment by franzholz** [comment]
Check it again with the latest version.

**Comment by webian** [comment]
Solved. Thanks.
