### ISSUE TITLE
No array key "name" in tt_products/api/class.tx_ttproducts_api.php

### ISSUE THREAD

**Issue by LightsOnDeveloper** [franzholz/tt_products#294]
Get this error in order process.

I did fast fix in line 1021 - 1027

`                            $emailArray = [$email];`
`                            //if (!empty($emailRow['name'])) {`
`                            //    $emailArray = [$email => $emailArray['name']];`
`                            //} else {`
`                            //    $emailArray = [$email];`
`                            //}`

**Comment by franzholz** [comment]
The name in the table _tt_products_emails_ must always be set at least to an empty string. So another fix must be done here.
