### ISSUE TITLE
Missing hook getItemMarkerArray?

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#3]
In version 2.7.23 there was a hook getItemMarkerArray in 
/view/class.tx_ttproducts_article_base_view.php

I used it heavily to make custom markers.
In version 2.8.1 this has been removed and my custom markers stopped to work.

Is there a replacement for this removed feature?
 
`

**Comment by webian** [comment]
nvm, I guess that I can use hook getRowMarkerArray in:
view/class.tx_ttproducts_table_base_view.php

**Comment by franzholz** [comment]
For the basket view you have the new hook getBasketView (formerly getItemMarkerArrays).
The getRowMarkerArrayHooks in view/class.tx_ttproducts_table_base_view.php are usable for every table of tt_products now, even categories. 

	foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF'][TT_PRODUCTS_EXT][$marker] as $classRef) {
		$hookObj = t3lib_div::getUserObj($classRef);

		if (method_exists($hookObj, 'getRowMarkerArray')) {
			$hookObj->getRowMarkerArray($pObj, $markerArray, $cObjectMarkerArray, $row, $imageNum, $imageRenderObj, $forminfoArray, $theCode, $id, $linkWrap);
		}
	}

**Comment by webian** [comment]
Thanks for the info.
Debugging I found that the hook getRowMarkerArray is called three times for each product in a list and then this happens again one more time.
So if I have 2 products then this hook is called 2x3x2=12 times.
Is this a normal behavior?

**Comment by webian** [comment]
Sorry, another question...
is there a way to have inside getRowMarkerArray a counter of the products listed?
So for every call of this hook I know that it's the product number 1,2,3... of the list

(With the old getItemMarkerArray I used the $id that now it no more a counter but a string like 'tt-products-list-110821')

**Comment by franzholz** [comment]
See file tt_products/view/class.tx_ttproducts_table_base_view.php:

getRowMarkerArrayHooks ($pObj, &$markerArray, &$cObjectMarkerArray, &$row, $imageNum, $imageRenderObj, &$forminfoArray, $theCode, $id, &$linkWrap)

You still have the $id as a parameter.

I have found the missing count here. (tt_products 2.8.9).
File class.tx_ttproducts_list_view.php Line 1550. Add the $iCount as parameter for $id.

	$itemTableView->getModelMarkerArray(
		$row,
		$itemTableViewArray[$itemTable->type]->getMarker(),
		$markerArray,
		$catTitle,
		$this->config['limitImage'],
		$image,
		$viewTagArray,
		array(),
		$theCode,
		$iCount, // neu FHO +++
		'',
		'',
		$imageWrap,
		TRUE,
		$TSFE->renderCharset
	);

**Comment by franzholz** [comment]
But why do you need the count? It is the wrong way to use the count for the identification of the product or for the id HTML attribute. You should use the uid of the product instead. Use the $row[uid] as the identifier. This is better. No product uid will come twice.

**Comment by franzholz** [comment]
But why do you need the count? It is the wrong way to use the count for the identification of the product or for the id HTML attribute. You should use the uid of the product instead. Use the $row[uid] as the identifier. This is better. No product uid will come twice.

**Comment by franzholz** [comment]
The Hook getRowMarkerArray is called twice for each product, because the fist call can be a merging of the article data with the product data, and the second is the original product data. Other calls come from the categories and maybe other tables involved. You can determine from the parent object $pObj and getModelObj() + getTablename() or by getMarker() which table you have.

**Comment by webian** [comment]
I need the count of products to divide products in columns in the list.
Using Twitter Bootstrap with adaptive graphic I have to add some .clearfix based on the actual product count.

Btw, I implemented my own counter and solved this.
Thanks for your kind help!
