### ISSUE TITLE
Composer installation fails due to duplicate class names

### ISSUE THREAD

**Issue by typecat** [franzholz/tt_products#31]
When installing via composer the console throws following errors:
`Warning: Ambiguous class resolution, "tx_ttproducts_variant_int" was found in both "/.../typo3conf/ext/tt_products/model/int.tx_ttproducts_variant_int.php" and "/.../typo3conf/ext/tt_products/model/interface.tx_ttproducts_variant_int.php", the first will be used.`
and
`Warning: Ambiguous class resolution, "tx_ttproducts_language" was found in both "$baseDir . '/web/typo3conf/ext/tt_products/lib/class.tx_ttproducts_language.php" and "/.../typo3conf/ext/tt_products/model/class.tx_ttproducts_language.php", the first will be used.`

**Comment by franzholz** [comment]
There is not file tt_products/model/int.tx_ttproducts_variant_int.php in tt_products 2.8.21.
There is not file tt_products/lib/class.tx_ttproducts_language.php in tt_products 2.8.21.

These files are only part of tt_products versions 2.7.x .
