### ISSUE TITLE
Version constraints in composer.json mustn't be empty

### ISSUE THREAD

**Issue by typecat** [franzholz/tt_products#32]
When installing via composer it complains about bad version constraints. It seems these empty version constraints are the problem:
`"require": {`
`    ...`
`    "typo3-ter/tsparser": ""`
`  },`
`  "suggest": {`
`    "typo3-ter/addons_em": ""`
`},`

As I have a patched version of EXT:tt_products my solution was setting `"typo3-ter/tsparser": "0.3.0"` and removing the suggest part.

Using TYPO3 8.7 composer mode and EXT:tt_products 2.8.21

**Comment by franzholz** [comment]
I think that this commit will solve it.

https://github.com/franzholz/tt_products/commit/8e0c55ff02f0904a207e2c41cf901033ada8c489
