### ISSUE TITLE
Plugin field "Product selection" order not considered

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#33]
If editor manually selects the products in field "Product selection" and orders them, the order is not respected.
This is because https://github.com/franzholz/tt_products/blob/79e9173653e41f9c030fec788dda03076d45e89b/view/class.tx_ttproducts_list_view.php#L464
that correctly set `$tableConfArray[$functablename]['orderBy']` to something like `FIELD(product.uid, 576,190,466,19,601)`
is then overwrite by https://github.com/franzholz/tt_products/blob/79e9173653e41f9c030fec788dda03076d45e89b/view/class.tx_ttproducts_list_view.php#L744
that set it to NULL

**Comment by franzholz** [comment]
This bugfix should solve this issue.

**Comment by webian** [comment]
I just tried again but it doesn't work as of today. 

I placed a plugin with display mode `Products: list` and selected some products in `Product selection` but in FE the products sorting of `Product selection` is not respected.

**Comment by franzholz** [comment]
Then there must somewhere be a second error. Check the SQL generation.

**Comment by webian** [comment]
I found where's the problem...
https://github.com/franzholz/tt_products/blob/d4a0acffba8e402a5d072a6c9facd37563db2813/view/class.tx_ttproducts_list_view.php#L1389 here 
`$queryParts['ORDERBY'] = 'product.sorting'`
instead, in this case, it should use MySQL's FIELD() function, so by example:
`$queryParts['ORDERBY'] = 'FIELD(uid,3,4,1,2)'`
where `3,4,1,2` is the list of uid sorted as the editor manually sorted in the BE. In practice what's inside $allowedItemArray

**Comment by webian** [comment]
I found the problem...

In this use case, there's a Typoscript `plugin.tt_products.conf.tt_products.ALL.orderBy = sorting` that disable the use of MySQL's FIELD() function that is already used in tt_products.

So to allow the plugin to be sorted manually I had to unset that Typoscript with `conf.tt_products.ALL.orderBy >` in the flexform `Typoscript` field of the plugin that must be sorted manually.

**Comment by franzholz** [comment]
Please add your use case to the wiki:
[tt_products TYPO3 Solutions](https://wiki.typo3.org/Tt_products#TYPO3_Solutions)
