### ISSUE TITLE
Missing error message if email not valid

### ISSUE THREAD

**Issue by sebkln** [franzholz/tt_products#34]
If I enter a wrong/incomplete email address during checkout, I get the inconclusive error message `field: ` from marker `###ERROR_DETAILS###`.

This is because the the lines 537-545 in `class.tx_ttproducts_control.php`:

	if (!$label) {
		$tmpArray = t3lib_div::trimExplode('|', tx_div2007_alpha5::getLL_fh003($langObj, 'missing'));
		$label = tx_div2007_alpha5::getLL_fh003($langObj, 'missing_' . $checkRequired);
		if ($label)	{
			$label = $tmpArray[0] .' '. $label . ' '. $tmpArray[1];
		} else {
			$label = 'field: '.$checkRequired;
		}
	}

Here the labels are built which could be overwritten by `_LOCAL_LANG`, but it currently only checks for `checkRequired`, not `checkAllowed`.

I tested this by simply replacing `checkRequired` with `checkAllowed` and got the normal error message with the language key `missing_email`.

So the code part above should be extended to check for both requirements and use a different prefix for `checkAllowed`, e.g. `invalid_`.

**Comment by franzholz** [comment]
Test the patch I have made.

**Comment by sebkln** [comment]
Wow, that was fast.

I tested the patch, works as expected. Thank you!
