### ISSUE TITLE
class.tx_ttproducts_email_view.php missing

### ISSUE THREAD

**Issue by typecat** [franzholz/tt_products#35]
In products list view following message is thrown by EXT:tt_products/lib/class.tx_ttproducts_tables.php Line 135-139:
>File not found: /xxx/typo3conf/ext/tt_products/view/class.tx_ttproducts_email_view.php in file class.tx_ttproducts_tables.php

Using:
* TYPO3 8.7.18
* EXT:tt_products 2.8.22
* EXT:div2007 1.9.0
* EXT:migration_core 0.1.3

**Comment by franzholz** [comment]
This is only a debug message with an information for the developer.
But this still should be fixed. So I have written a patch.

**Comment by typecat** [comment]
I've tested - works ;)
