### ISSUE TITLE
PHP Runtime Deprecation Notice

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#4]
I get this in php error log:
`core: Core: Error handler (FE): PHP Runtime Deprecation Notice: Non-static method tx_ttproducts_field_price_view::priceFormat() should not be called statically in ../ext/tt_products/view/field/class.tx_ttproducts_field_price_view.php line 155

**Comment by webian** [comment]
also:
public **static** function printPrice ($priceText, $taxInclExcl = '')

**Comment by franzholz** [comment]
I have fixed this PHP 7 related error now.

https://github.com/franzholz/tt_products/commit/98012cb853a4c78edc44611217a7c7f1a421ac15
