### ISSUE TITLE
Typo3 9.x compatibility

### ISSUE THREAD

**Issue by rfc2822** [franzholz/tt_products#42]
Hello,

Are there plans to make tt_products compatible with Typo3 9.x? Maybe in the paid version?

**Comment by franzholz** [comment]
Yes, TYPO3 9 support will be coming for tt_products versions 2.9.x and later. However, I am busy at the moment.

**Comment by rfc2822** [comment]
Thanks for the information! So I'll stay at 8.x in the meanwhile, which is LTS anyway :)

**Comment by franzholz** [comment]
Now tt_products 2.9.7 is published. It works under TYPO3 9.5.
