### ISSUE TITLE
double exclude.sys_products_orders

### ISSUE THREAD

**Issue by TrueType** [franzholz/tt_products#45]
https://github.com/franzholz/tt_products/blob/a91021fdff32b231fb10f558dd4e1124e3392b84/ext_conf_template.txt#L42

I guess this setting is responsible for in the latest version the client_ip may not be stored in sys_products_orders any more. But well, that's of topic...

**Comment by franzholz** [comment]
The duplicate wrong entry has been fixed now.

https://github.com/franzholz/tt_products/pull/46
