### ISSUE TITLE
Validation message always shown for check order when a user is not logged in

### ISSUE THREAD

**Issue by Georgyge** [franzholz/tt_products#47]
I am using TYPO3 6.2.40 and tt_products 2.7.14. For me, everything works fine when a user is logged in and order something.
But the problem is, if a user is not logged in (ie. as a guest) and if they order something and after clicking "check order", a validation message is always shown as 
" _Please enter your address!_ "
if 
`plugin.tt_products.requiredInfoFields = address,zip,city,email`
is set. Evenif I enter the address, I get this error.

Whether am I missing any configuration from my part? What may be the issue?

**Comment by Georgyge** [comment]
Worked. Thank you!

**Comment by daeff** [comment]
@franzholz could you please update this link? https://wiki.typo3.org/Tt_products
I currently have a similar problem and the link here doesnt work anymore.

Thanks

**Comment by franzholz** [comment]
The Wiki is here beneath Github now on the top right tab.
