### ISSUE TITLE
Error 500 when creating relation product<>article

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#5]
In the BE, when I try to create a relation products to articles I get a:
`Error 500 Internal Server Error`

In detail, apache log shows:
`10.0.0.100 - - [27/Jul/2016:12:30:29 +0200] "POST /typo3/index.php?ajaxID=%2Fajax%2Frecord%2Finline%2Fcreate&ajaxToken=cc398ac2f6b39a9a031a14eacf0624722df66247 HTTP/1.1" 500 9922 "http://l.test.com/typo3/index.php?route=%2Frecord%2Fedit&token=149579b5ab37255e44c64a8b2694e43132dfc11f&edit[tt_products][110447]=edit&returnUrl=%2Ftypo3%2Findex.php%3FM%3Dweb_list%26moduleToken%3Dff54740ece6050f6cb044a4a4d376aee23ce9dbd%26id%3D100033%26imagemode%3D1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"`

and php log
`[27-Jul-2016 12:30:31 Europe/Berlin] http://l.test.com/ - Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1438185331: At least one "types" array must be defined for table tt_products_products_mm_articles, preferred "0" | UnexpectedValueException thrown in file /typo3/sysext/backend/Classes/Form/FormDataProvider/DatabaseRecordTypeValue.php in line 43. Requested URL: http://l.test.com/typo3/index.php?ajaxID=%2Fajax%2Frecord%2Finline%2Fcreate&ajaxToken=cc398ac2f6b39a9a031a14eacf0624722df66247`

I set up tt_products with articleMode = 2

The vm has PHP 7 and TYPO3 7.6.10-dev

**Comment by franzholz** [comment]
You must not edit the relation table "products to articles" directly.  You must add the articles on the product entry form.

**Comment by webian** [comment]
That's what I do.
If I click the button "Create new Relation products to articles" or the button "Create new relation" that I find in the tab "Relations" when I edit a product, I get the errors.

**Comment by franzholz** [comment]
I have fixed this TYPO3 7.6.10 problem now:

https://github.com/franzholz/tt_products/commit/7754c52852022adb08ca6c7ac0d111fb8542c329
