### ISSUE TITLE
Variable $language in class.tx_ttproducts_marker.php is not set

### ISSUE THREAD

**Issue by responseinformationsdesign** [franzholz/tt_products#53]
As variable $language in class.tx_ttproducts_marker.php is not set (since version 2.9.6) always the markerFile for the default language is chosen (locallang.xml).

**Comment by franzholz** [comment]
Please test, if it is working now.

**Comment by responseinformationsdesign** [comment]
With patch applied labels are shown in the correct language again. Therefore issue can be closed.

Thanks!
