### ISSUE TITLE
Subtemplates are not taken into account

### ISSUE THREAD

**Issue by responseinformationsdesign** [franzholz/tt_products#54]
Although a subtemplate is defined (f. e. plugin.tt_products.templateFile.BASKET) only(!) the subpart of the main template is used (plugin.tt_products.templateFile).
Problem exists since version 2.9.6.

**Comment by franzholz** [comment]
It seems that your path to the template file is wrong.
I have added a patch for a better error message if something is wrong with the path to the templateFile.

**Comment by responseinformationsdesign** [comment]
As subtemplates work flawlessly with version 2.9.5 I think the typoscript configuration should be OK.

**Comment by responseinformationsdesign** [comment]
Error message 

`Produkte: Der Bereich ###BASKET_TEMPLATE### wurde in der Template Datei EXT: <pathToFile>/basket.html nicht gefunden.`

shows that subtemplate is used (and found) but marker  ###BASKET_TEMPLATE###  can´t be detected.

But basket.html definitely contains ###BASKET_TEMPLATE###.

**Comment by responseinformationsdesign** [comment]
Identical issue now for subtemplate ###BASKET_INFO_TEMPLATE### (tt_producs 2.9.10)

Content of plugin.tt_products.templateFile is used instead of plugin.tt_products.templateFile.BASKET.

**Comment by franzholz** [comment]
I do not understand. Why should a template setup plugin.tt_products.templateFile.BASKET be used for the INFO code?

**Comment by responseinformationsdesign** [comment]
This was just the behaviour up to now. 

BTW: it´s BASKET_INFO not just INFO

**Comment by responseinformationsdesign** [comment]
Bug is still present in version 2.9.12

**Comment by franzholz** [comment]
Give more details. I cannot reproduce a problem to this case any more.

**Comment by responseinformationsdesign** [comment]
Bug still present in version 2.9.16

TypoScript configuration:
```
plugin.tt_products {
  templateFile = EXT:theme_bootstrap_site/Resources/Private/Extensions/TtProducts/Templates/default.html
  templateFile.BASKET = EXT:theme_bootstrap_site/Resources/Private/Extensions/TtProducts/Templates/basket.html
}
```

Subtemplate `BASKET_INFO_TEMPLATE` of `default.html` is used instead of that one in `basket.html`

If subtemplate `BASKET_INFO_TEMPLATE` is missing in `default.html` -> `Produkte: Der Bereich ###BASKET_INFO_TEMPLATE### wurde in der Template Datei EXT:theme_bootstrap_site/Resources/Private/Extensions/TtProducts/Templates/default.html nicht gefunden.`

But file `basket.html` is also taken into account. If missing -> `Produkte: Die Shop-Template Datei wurde nicht gefunden. Überprüfen Sie im Template Setup: plugin.tt_products.BASKET.templateFile = EXT:theme_bootstrap_site/Resources/Private/Extensions/TtProducts/Templates/basket.html`

**Comment by franzholz** [comment]
You must use this TypoScript, if you want to use the basket.html template also for the INFO code:

    plugin.tt_products {
    templateFile = EXT:theme_bootstrap_site/Resources/Private/Extensions/TtProducts/Templates/default.html
    templateFile.BASKET = EXT:theme_bootstrap_site/Resources/Private/Extensions/TtProducts/Templates/basket.html
    templateFile.INFO = EXT:theme_bootstrap_site/Resources/Private/Extensions/TtProducts/Templates/basket.html
    }

The behaviour of tt_products is correct. It always uses the default template file if no template for a code has been assigned. Each code must be configured in this setup, if another template shall be used for it.

**Comment by responseinformationsdesign** [comment]
Thank you! This did the job.
I thought `templateFile.BASKET` would cover all subtemplates containing `"BASKET"`.
