### ISSUE TITLE
Impossible to change wrap of shipping/payment select

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#59]
https://github.com/franzholz/tt_products/blob/d51b437cb448844f10b295c8729adf9cbf5a0417/lib/class.tx_ttproducts_paymentshipping.php#L443 here `$confArray['wrap']` is always not set because it has been unset by cleanConfArr().

The old version that checked `$this->conf[$pskey.'.']['wrap']` was working.

**Comment by franzholz** [comment]
The configuration cleaner method must be executed on a later place.

    $confArray = tx_ttproducts_control_basket::cleanConfArr($confArray);
