### ISSUE TITLE
Question: how to hide prices?

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#6]
I would like to use the same templates for different sites. Some of these sites need to not display prices.
So I'm wondering what's the best way to not show prices without create a custom template that have not the prices markers?

In general, I think that the best way would be to use a typoscript constant that turns on/off a particular marker or a series of markers. But is this possible with tt_products 2.8?

Thanks in advance for any help!

**Comment by franzholz** [comment]
You can use "usePriceTag=1" and your own "priceTagObj" setup to modify the output of the prices by your own Typoscript. By default it is an IMAGE, however you could use a TEXT as well. Build a TEXT which bases on your own defined constant.
Markers of the priceTagObj are ###PRICE### and ###TAX_INCL_EXCL###

**Comment by webian** [comment]
Thank you for the info Franz but unfortunately it's not enough in my case cause I need to hide other markers, not only the price markers.

I need something like the markers  that turn on/off a template subpart.

Btw, if it's not possible to make custom markers like these I can work with hook getRowMarkerArray even if I find this solution less elegant.

Thank you anyway!
