### ISSUE TITLE
TYPO3 9 - Warnings because Typoscript condition could not be parsed

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#68]
[WARNING] request="3ad7acfbac869" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = GP:ttp_basket != ''"}
[WARNING] request="3ad7acfbac869" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalString = GP:tt_products|sword = /.+/"}
[WARNING] request="3ad7acfbac869" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalString = GP:sword = /.+/"}

**Comment by franzholz** [comment]
Fixed in tt_products 2.9.13
