### ISSUE TITLE
Same requiredInfoFields for billing and delivery

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#7]
If I well understood the code, the required delivery fields are checked against the typoscript setup 'requiredInfoFields' that are used also for required billing fields.
Shouldn't the required fields for billing and delivery be independent?

By instance, I have required 'first_name' and 'last_name' fields in billing but only 'name' field for delivery. Also I don't have any required field in delivery. So if a user inputs something in the delivery fields the code search for a 'first_name' and 'last_name' required fields in delivery and it can't found them compiled so the user can't proceed with the order.

**Comment by franzholz** [comment]
This feature is already implemented in tt_products 2.9.1 .

**Comment by webian** [comment]
tt_products 2.9.1 ?
Sorry, I see a branch 2.9.0 and it's for TYPO3 4.6

**Comment by franzholz** [comment]
tt_products 2.9.1 is available at http://ttproducts.de/tt_products_ext.html?&tt_products[product]=24 .

**Comment by webian** [comment]
Got it thanks.
