### ISSUE TITLE
Email address with double consecutive underscore

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#75]
The regular expression that checks the validity of email addresses incorrectly considers an email address with double consecutive underscores to be wrong.

https://regex101.com/r/AEUhty/1/

**Comment by franzholz** [comment]
Do you have a bug fix for it?

**Comment by webian** [comment]
Not atm but I suggest to use [filter_var() function](https://stackoverflow.com/a/12026863/1463262) instead of regex.

**Comment by webian** [comment]
If you still want to use regex I made [this RFC5322 regex](https://regex101.com/r/0ZjWb2/2) ready to be copy/pasted [here ](https://github.com/franzholz/tt_products/blob/666fddf5b07229ced1837b001e2a18e6c1702f95/Configuration/TypoScript/PluginSetup/Main/setup.txt#L551)

(credit goes to https://regex101.com/library/gJ7pU0 where I started from)

**Comment by franzholz** [comment]
I want to have an easy understandable solution based on regexp.
I have taken it from here:

https://www.emailregex.com/  

Please test it!

**Comment by webian** [comment]
It's not bullet-prof like the RFC5322 regex that I suggested but I think it's enough for e-commerce cases.

**Comment by babaralishah** [comment]
Hi 
I am on Angular

And using the below regex:

`'^[a-z0-9]+([._-]?[a-z0-9]+)+@[a-z0-9]+([._-]?[a-z0-9]+)+\\.[a-z]{2,3}$'`

But its not fulfilling my requirement, my requirement is below:

`saa5@me-d_d_u.co`

please anyone tell me, why this regex is not working for my above mentioned case.

Regards
Babar Ali Shah

**Comment by franzholz** [comment]
This part `[._-]?` means that only a maximum of one of these characters is allowed.
You must use a `*` instead of the `?` .

**Comment by babaralishah** [comment]
> This part `[._-]?` means that only a maximum of one of these characters is allowed. You must use a `*` instead of the `?` .

Thank you Sir!

This below Regex is working fine:

^\w+([\.-]?\w+)+@[\w.-]+([\.-]?\w+)(\.\w{2,3})+$

Use-Case:

babar.ali.shah-512_me.you_ir-getme@gmail-here-there.where_any.resource_avavilable.com
