### ISSUE TITLE
Setup marks not more parsed

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#76]
Since tt_products 2.9.11 what is setup in plugin.tt_products.marks is no more parsed and it's displayed as ###THE_MARKER### in frontend output instead of the parsed value.

More specifically the bug has been introduced with this commit: https://github.com/franzholz/tt_products/commit/bac8dc9ed12a09141db886018eae01c9bc4a765d

Are there any undocumented breaking changes?

**Comment by webian** [comment]
> The file _tx_ttproducts_marker.php_ is responsible for this. The patch which you mean has no change in this file.

`tx_ttproducts_marker` is not an isolated class, it interacts with data coming from other classes (i.e.: `tx_ttproducts_config`). The fact that `tx_ttproducts_marker` has not been changed doesn't mean that is not affected.

If I check out the commit before https://github.com/franzholz/tt_products/commit/bac8dc9ed12a09141db886018eae01c9bc4a765d then markers set with typoscript work, if I check out https://github.com/franzholz/tt_products/commit/bac8dc9ed12a09141db886018eae01c9bc4a765d they are not parsed anymore.

Before that commit, [here](https://github.com/franzholz/tt_products/blob/0dc66c74feddbbea56bcff7e1cc8e85e643752b5/marker/class.tx_ttproducts_marker.php#L68) $cnf has the configurations, after that commit $cnf has null elements.

Maybe you can't reproduce this bug because you use tt_products in a different way than me (aka: different setup and configuration) but that commit changed something that broke tt_products output in my setup.

**Comment by webian** [comment]
Before https://github.com/franzholz/tt_products/commit/bac8dc9ed12a09141db886018eae01c9bc4a765d, https://github.com/franzholz/tt_products/blob/0dc66c74feddbbea56bcff7e1cc8e85e643752b5/lib/class.tx_ttproducts_config.php#L51 is called by tx_ttproducts_control_creator. Consequently, tx_ttproducts_config $conf and $config are set.

After https://github.com/franzholz/tt_products/commit/bac8dc9ed12a09141db886018eae01c9bc4a765d, tx_ttproducts_marker is now instantiated inside tx_ttproducts_control_creator before tx_ttproducts_config->init so I don't even know how can this bug not happen to someone else.

Btw, I give up. This extension has reached a level of messy spaghetti code so high that is now impossible to debug. Better us this time to migrate to another solution.

**Comment by franzholz** [comment]
Please test the bugfix!

**Comment by webian** [comment]
Ok, fixed.
