### ISSUE TITLE
Ordered products are no more displayed in BE order detail

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#79]
In TYPO3 9 LTS backend, opening an order in list view, it was possible to see the ordered products (TCA field `ordered_products`) at the end.
Now the ordered products are no more displayed.

**Comment by franzholz** [comment]
I have removed the feature static_taxes, because it did only support a very old version of the extension static_info_tables_taxes. The full support of the newest version of static_info_tables_taxes is available in future versions of tt_products: version 2.13.2 and higher.

**Comment by webian** [comment]
Now the ordered products are displayed again but it's missing the bought quantity.

**Comment by franzholz** [comment]
I have added the product count.

https://github.com/franzholz/tt_products/commit/29442d28e384b718b80e3adceb072eee85e301d8

**Comment by webian** [comment]
Ok but if an article has been ordered it displays its parent product not the article.

**Comment by franzholz** [comment]
Only products can be ordered. Articles are to have different prices for product variants.
You can contribute a better PHP code for the order product list. This is just a first version of it.

**Comment by webian** [comment]
ok
