### ISSUE TITLE
tt_products - MySQL 5.7

### ISSUE THREAD

**Issue by SvenIgnor** [franzholz/tt_products#8]
Hello Mr. Holzinger (@franzholz),

we have multiple running tt_products-Shops (2.7.17 & 2.11.0) and tried to migrate them to MySQL 5.7 (with default-settings).
Long story short, two errors occur in the SQL-debug and lead to blank product-lists:

2.7.17:
Error 1: Expression #1 of ORDER BY clause is not in SELECT list, references column 'project1.tt_products_cat.sorting' which is not in SELECT list; this is incompatible with DISTINCT

2.11.0:
Error 2: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'project2.mm.sorting' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Unfortunatily deactivating or changing the required options is not an alternative.

Is there a plan to fix this? We appreciate a proposed solution.

Thank you for your great work.

Best regards

**Comment by franzholz** [comment]
Which setup did you use? How can I reproduce this?
What is the full SQL error message? Do you have a backtrace path to the SQL error?

**Comment by franzholz** [comment]
You can add any missing field names by Typoscript:

```
plugin.tt_products {

 conf.tt_products.ALL {
    requiredFields := addToList(sorting)
}
}

```
