### ISSUE TITLE
###ORDER_UID### doesn't contain the order uid anymore

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#80]
###ORDER_UID### doesn't contain the order uid anymore

**Comment by webian** [comment]
This happen in finalize.

**Comment by webian** [comment]
And it's probably caused by this commit https://github.com/franzholz/tt_products/commit/8fbe7b23cf4a06471e1552fca7a4c317d6eb270a
because the orderUid is cleared before rendering the template.

**Comment by webian** [comment]
And also because the ORDER_UID marker is used inside BASKET_ORDERCONFIRMATION_NOSAVE_TEMPLATE. So probably this is not a bug.

**Comment by webian** [comment]
Summarizing...

###ORDER_UID### doesn't contain the order uid if used inside BASKET_ORDERCONFIRMATION_NOSAVE_TEMPLATE.

**Comment by franzholz** [comment]
Is the ###ORDER_UID###  correct, after this fix?

**Comment by webian** [comment]
This https://github.com/franzholz/tt_products/commit/a1dfbb2c83773713d66ea7592696b7b4ce279712 not only doesn't solve the bug but also is missing a semicolon https://github.com/franzholz/tt_products/blob/a1dfbb2c83773713d66ea7592696b7b4ce279712/view/class.tx_ttproducts_order_view.php#L59 causing `syntax error, unexpected '$markerArray' (T_VARIABLE)`

Evidently this extension is developed blindly without the slightest testing.

**Comment by franzholz** [comment]
Why does this fix not solve the bug?
';' added.

**Comment by webian** [comment]
> ###ORDER_UID### doesn't contain the order uid if used inside BASKET_ORDERCONFIRMATION_NOSAVE_TEMPLATE.

Because this still happens.

**Comment by franzholz** [comment]
The initialization of the $orderArray has been forgotten. It is only available on the finalize page. This can be improved.

**Comment by franzholz** [comment]
https://github.com/franzholz/tt_products/commit/642635cedf15539d10ba86519c8bcea7461b0370

**Comment by webian** [comment]
ok
