### ISSUE TITLE
Invalid database result detected:

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#81]
class.tx_ttproducts_graduated_price.php throws error:
`Invalid database result detected: function TYPO3\CMS\Typo3DbLegacy\Database\DatabaseConnection->sql_free_result called from file l/class.tx_ttproducts_graduated_price.php in line 120`

The SQL generated by method `getFormulasByProduct` is:
```
SELECT
	tt_products_graduated_price.uid uid,
	tt_products_graduated_price.pid pid,
	tt_products_graduated_price.tstamp tstamp,
	tt_products_graduated_price.crdate crdate,
	tt_products_graduated_price.deleted deleted,
	tt_products_graduated_price.sorting sorting,
	tt_products_graduated_price.hidden hidden,
	tt_products_graduated_price.starttime starttime,
	tt_products_graduated_price.endtime endtime,
	tt_products_graduated_price.fe_group fe_group,
	tt_products_graduated_price.title title,
	tt_products_graduated_price.formula formula,
	tt_products_graduated_price.startamount startamount,
	tt_products_graduated_price.note note
FROM
	tt_products_graduated_price
INNER JOIN tt_products_mm_graduated_price ON
	tt_products_graduated_price.uid = tt_products_mm_graduated_price.graduated_price_uid
WHERE
	1 = 1
	AND tt_products_graduated_price.deleted = 0
	AND tt_products_graduated_price.hidden = 0
	AND (tt_products_graduated_price.starttime <= 1616688707)
	AND (tt_products_graduated_price.endtime = 0
	OR tt_products_graduated_price.endtime>1616688707)
	AND tt_products_graduated_price.fe_group IN (' ', 0,-1)
	AND tt_products_mm_graduated_price.deleted = 0
	AND tt_products_mm_graduated_price.hidden = 0
```

this query is wrong because field `tt_products_mm_graduated_price.graduated_price_uid` has been renamed to `tt_products_mm_graduated_price.uid_foreign`

**Comment by webian** [comment]
Searching the extension code for the string `graduated_price_uid` there are other places where this has not been updated after https://github.com/franzholz/tt_products/commit/afac012c8fca5bf1a36a10c0ac1fba9d633f21d7 

Eg: tt_products/Configuration/TCA/tt_products_mm_graduated_price.php:22

**Comment by franzholz** [comment]
Please test it. I do not have an environment for testing the price tables.

**Comment by webian** [comment]
I don't have an environment to test graduated price too but it seems that this error is fixed.
