### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#82]
Testing tt_products in TYPO3 10 LTS and PHP 7.4, I get these warnings in basket:
[WARNING] request="b9550c0ae89e6" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (FE): PHP Warning: count(): Parameter must be an array or an object that implements Countable in /ext/tt_products/view/class.tx_ttproducts_basket_view.php line 179

This is because here https://github.com/franzholz/tt_products/blob/b7eb5d82c92de0075faf528ecaf22a91b1f529d0/view/class.tx_ttproducts_basket_view.php#L179 $orderArray is null.

Maybe use is_array() in place of count()?

**Comment by franzholz** [comment]
This issue has been fixed by `empty()` instead of `!count()`.

**Comment by webian** [comment]
ok
