### ISSUE TITLE
"Product record" TCA field search wizard not working

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#87]
While editing tt_products_language record in BE, the search wizard for field `Product record` (prod_uid) doesn't work.

Removing ###STORAGE_PID### in TCA makes it work again:
from:
`'foreign_table_where' => 'AND tt_products.pid IN (###CURRENT_PID###,###STORAGE_PID###) ORDER BY tt_products.uid',`
to:
`'foreign_table_where' => 'AND tt_products.pid IN (###CURRENT_PID###) ORDER BY tt_products.uid',`

Note: similar problem for other table that has `###STORAGE_PID###`.

**Comment by webian** [comment]
I guess `###STORAGE_PID###` [has been deprecated in TYPO3 7.4](https://stackoverflow.com/questions/40735973/typo3-generalstoragefolder-is-gone-how-to-get-storagepid-inside-plugin-flexform) but I can't find the documentation.

**Comment by franzholz** [comment]
Unfortunately the Core developers have removed the possibility to store records in a storage page sysfolder. So this feature must also be removed again from tt_products.
