### ISSUE TITLE
PHP Warnings: Declaration should be compatible

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#9]
Hello,
I found many PHP warnings (list follows) that are filling the php log and mysql syslog table.
Is it possible to do something to get rid of these warnings?

> PHP Warning: Declaration of tx_ttproducts_address::init(&$pibase, $functablename) should be compatible with tx_ttproducts_table_base::init($cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_address.php line 114
> PHP Warning: Declaration of tx_ttproducts_article::init($cObj, $functablename) should be compatible with tx_ttproducts_article_base::init(&$cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_article.php line 0
> PHP Warning: Declaration of tx_ttproducts_article::init($cObj, $functablename) should be compatible with tx_ttproducts_article_base::init(&$cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_article.php line 144
> PHP Warning: Declaration of tx_ttproducts_article_base::init(&$cObj, $functablename) should be compatible with tx_ttproducts_table_base::init($cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_article_base.php line 45
> PHP Warning: Declaration of tx_ttproducts_article_base_view::getItemSubpartArrays($templateCode, $functablename, &$row, &$subpartArray, &$wrappedSubpartArray, &$tagArray, $theCode = '', $id = '1') should be compatible with tx_ttproducts_table_base_view::getItemSubpartArrays(&$templateCode, $functablename, $row, &$subpartArray, &$wrappedSubpartArray, &$tagArray, $theCode = '', $id = '') in htdocs/ext/tt_products/view/class.tx_ttproducts_article_base_view.php line 41
> PHP Warning: Declaration of tx_ttproducts_article_view::init(&$langObj, &$modelObj) should be compatible with tx_ttproducts_article_base_view::init($langObj, $modelObj) in htdocs/ext/tt_products/view/class.tx_ttproducts_article_view.php line 0
> PHP Warning: Declaration of tx_ttproducts_article_view::init(&$langObj, &$modelObj) should be compatible with tx_ttproducts_article_base_view::init($langObj, $modelObj) in htdocs/ext/tt_products/view/class.tx_ttproducts_article_view.php line 55
> PHP Warning: Declaration of tx_ttproducts_field_image::init(&$cObj) should be compatible with tx_ttproducts_field_media::init($cObj) in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_image.php line 43
> PHP Warning: Declaration of tx_ttproducts_field_media::init($cObj) should be compatible with tx_ttproducts_field_base::init($cObj, $bUseStaticTaxes, $uidStore) in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_media.php line 0
> PHP Warning: Declaration of tx_ttproducts_field_tax::init($cObj, $bUseStaticTaxes, $uidStore) should be compatible with tx_ttproducts_field_base::init($cObj) in htdocs/ext/tt_products/model/field/class.tx_ttproducts_field_tax.php line 40
> PHP Warning: Declaration of tx_ttproducts_orderaddress::get($uid) should be compatible with tx_ttproducts_table_base::get($uid = '0', $pid = 0, $bStore = true, $where_clause = '', $groupBy = '', $orderBy = '', $limit = '', $fields = '', $bCount = false, $aliasPostfix = '', $fallback = false) in htdocs/ext/tt_products/model/class.tx_ttproducts_orderaddress.php line 0
> PHP Warning: Declaration of tx_ttproducts_orderaddress::get($uid) should be compatible with tx_ttproducts_table_base::get($uid = '0', $pid = 0, $bStore = true, $where_clause = '', $groupBy = '', $orderBy = '', $limit = '', $fields = '', $bCount = false, $aliasPostfix = '', $fallback = false) in htdocs/ext/tt_products/model/class.tx_ttproducts_orderaddress.php line 193
> PHP Warning: Declaration of tx_ttproducts_orderaddress_view::getRowMarkerArray(&$row, &$markerArray, $bSelect, $type) should be compatible with tx_ttproducts_table_base_view::getRowMarkerArray(&$row, $markerKey, &$markerArray, &$variantFieldArray, &$variantMarkerArray, &$tagArray, $theCode, $bHtml = true, $charset = '', $imageNum = 0, $imageRenderObj = 'image', $id = '', $prefix = '', $suffix = '', $linkWrap = '') in htdocs/ext/tt_products/view/class.tx_ttproducts_orderaddress_view.php line 0
> PHP Warning: Declaration of tx_ttproducts_orderaddress_view::getRowMarkerArray(&$row, &$markerArray, $bSelect, $type) should be compatible with tx_ttproducts_table_base_view::getRowMarkerArray(&$row, $markerKey, &$markerArray, &$variantFieldArray, &$variantMarkerArray, &$tagArray, $theCode, $bHtml = true, $charset = '', $imageNum = 0, $imageRenderObj = 'image', $id = '', $prefix = '', $suffix = '', $linkWrap = '') in htdocs/ext/tt_products/view/class.tx_ttproducts_orderaddress_view.php line 141
> PHP Warning: Declaration of tx_ttproducts_page::get($uid = 0, $pid = 0, $bStore = true, $where_clause = '', $limit = '', $fields = '', $bCount = false) should be compatible with tx_ttproducts_table_base::get($uid = '0', $pid = 0, $bStore = true, $where_clause = '', $groupBy = '', $orderBy = '', $limit = '', $fields = '', $bCount = false, $aliasPostfix = '', $fallback = false) in htdocs/ext/tt_products/model/class.tx_ttproducts_page.php line 45
> PHP Warning: Declaration of tx_ttproducts_page::init(&$pibase, $tablename) should be compatible with tx_ttproducts_table_base::init($cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_page.php line 45
> PHP Warning: Declaration of tx_ttproducts_product::init($cObj, $functablename = 'tt_product...') should be compatible with tx_ttproducts_article_base::init(&$cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_product.php line 40
> PHP Warning: Declaration of tx_ttproducts_static_tax::init(&$pibase, $functablename) should be compatible with tx_ttproducts_table_base::init($cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_static_tax.php line 0
> PHP Warning: Declaration of tx_ttproducts_static_tax::init(&$pibase, $functablename) should be compatible with tx_ttproducts_table_base::init($cObj, $functablename) in htdocs/ext/tt_products/model/class.tx_ttproducts_static_tax.php line 252

**Comment by webian** [comment]
I add that these warnings are logged even if $GLOBALS['TYPO3_CONF_VARS']['SYS']['systemLogLevel'] is set to 3 (error).

**Comment by webian** [comment]
I found that these PHP7 warnings can be fixed giving default values to the additional parameters:
http://stackoverflow.com/a/37081778/1463262

Could this be a viable solution?

**Comment by franzholz** [comment]
I have made 2 commits. Check this out.

https://github.com/franzholz/tt_products/commit/54826e5631d9c825cc705b5d1a5b588b2000eb96
https://github.com/franzholz/tt_products/commit/4d896ed247fcdb75bd0528d30aafcf05a1ed0dee

**Comment by webian** [comment]
Great! Thank you!
