### ISSUE TITLE
Products not visible because of forced values in fields sellendtime and/or endtime

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#90]
Probably after the introduction of this https://github.com/TYPO3/TYPO3.CMS/commit/adce6dbe8b305c71c447929bc14e5c87b4ad6954 when a product is saved and fields sellendtime and/or endtime are empty, their values are forced to the date of one month before today and the product is then not visible in the FE.

This is because of TCA config:
```
'range' => array (
    'upper' => mktime(0, 0, 0, 12, 31, 2300),
    'lower' => mktime(0, 0, 0, date('n') - 1, date('d'), date('Y'))
)
```

I suggest to remove these unnecessary 'range' configurations in the TCA config of the various tables not only tt_products.

**Comment by franzholz** [comment]
Then this is a bug in TYPO3 which you should report there.
The range must not set a default value.

**Comment by franzholz** [comment]
The range feature must work also in newer versions of TYPO3. It is no solution to remove this from tt_products. The default range can be overwritten anyways by TS Config.

**Comment by quadronet** [comment]
Wie kann man das für tt_products lösen? So kann der Kunde kein Produkt mehr bearbeiten. 
Beispielcode?

**Comment by franzholz** [comment]
Only English here!

**Comment by quadronet** [comment]
**I found this in TYPO3 Bugtracker:**
https://forge.typo3.org/issues/82756
https://review.typo3.org/c/Packages/TYPO3.CMS/+/70232/1/typo3/sysext/core/Classes/DataHandling/DataHandler.php

replace this line in
typo3/sysext/core/Classes/DataHandling/DataHandler.php 

-> for T3 Version 10.4 in line 1921:         if (isset($tcaFieldConf['range']) && is_array($tcaFieldConf['range'])) {
-> for T3 Version 11 in line 1745

**with this part:** 

        // Skip range validation, if the default value equals 0 and the input value is 0, "0" or an empty string.
        // This is needed for timestamp date fields with ['range']['lower'] set.
        $skipRangeValidation =
            isset($tcaFieldConf['default'])
            && (int)$tcaFieldConf['default'] === 0
            && ($res['value'] === '' || $res['value'] === '0' || $res['value'] === 0);

        // Checking range of value:
        if (!$skipRangeValidation && isset($tcaFieldConf['range']) && is_array($tcaFieldConf['range'])) {

**Comment by franzholz** [comment]
A 3rd patchset is available:

[3rd patch 70232: BUGFIX Skip range validation if input value and default are both "0"](https://review.typo3.org/c/Packages/TYPO3.CMS/+/70232/3/typo3/sysext/core/Classes/DataHandling/DataHandler.php)

**Comment by webian** [comment]
Tested with today TYPO3 10.4.19 release and this bug is solved so I close it.
