### ISSUE TITLE
###PRODUCT_DATASHEET### from old templates doesn´t work anymore in tt-product 3.2.1

### ISSUE THREAD

**Issue by quadronet** [franzholz/tt_products#96]
``###PRODUCT_DATASHEET### from old templates doesn´t work anymore in tt-product 3.2.1. 
``
` 	 
 <p><b>Info-Download:</b> </p>
	<ul class="csc-uploads csc-uploads-1" style="list-style: none;">
    <li class="li-odd li-first csc-uploads-element csc-uploads-element-pdf"><img src="fileadmin/templates/images/pdf.png" width="48" height="48" alt="Download"><span class="csc-uploads-fileName">###PRODUCT_DATASHEET### </span>
     
        </li>
        </ul>
   `

The name of the file isn´t shown, but the marker is linked to pdf without filename:  ###PRODUCT_LINK_DATASHEET###

**Comment by franzholz** [comment]
You must migrate the datasheets to the FAL in the Install Tool.
