### ISSUE TITLE
Commit: "add step to version 2.13.2"

### ISSUE THREAD

**Issue by webian** [franzholz/tt_products#99]
Was [this commit](https://github.com/franzholz/tt_products/commit/7943f43c749946e86e8f3ea7fd1bd2c7751ebd98) done by mistake or did you really want to "step" from version 2.9 to 2.13 in a single undocumented commit of 334 changed files with 38,498 additions and 17,193 deletions?

**Comment by webian** [comment]
nvm

**Comment by franzholz** [comment]
2.9 has gotten its own branch now again.

version2_9_0

Only bug fixes will come into version 2.9.x. No support for future versions after TYPO3 10.4. 

All development will be done only in these versions 
2.13 and later.
3.2 and alter.
4.0: This will be a rewrite for Extbase/Fluid.
